function byLanguage(a, b) {
  if (a.name > b.name) {
    return 1;
  } else if (a.name < b.name) {
    return -1;
  } else {
    return 0;
  }
  return 0
}

var regionSegments =  [{"from":"Carrib.","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":15000},
{"from":"Carrib.","to":"Panama","cabin":"Economy","award":"Saver","price":7500},
{"from":"Carrib.","to":"Carrib.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Carrib.","to":"Colom.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Carrib.","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Carrib.","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Carrib.","to":"Mexico","cabin":"Economy","award":"Saver","price":12500},
{"from":"Carrib.","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"Carrib.","to":"Panama","cabin":"Economy","award":"Standard","price":15000},
{"from":"Carrib.","to":"Carrib.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Carrib.","to":"Colom.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Carrib.","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Carrib.","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Carrib.","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"Carrib.","to":"Mexico","cabin":"Economy","award":"Standard","price":25000},
{"from":"Carrib.","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"Carrib.","to":"Carrib.","cabin":"Business","award":"Saver","price":25000},
{"from":"Carrib.","to":"Colom.","cabin":"Business","award":"Saver","price":25000},
{"from":"Carrib.","to":"N. S Amer.","cabin":"Business","award":"Saver","price":25000},
{"from":"Carrib.","to":"Panama","cabin":"Business","award":"Saver","price":20000},
{"from":"Carrib.","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Carrib.","to":"Mexico","cabin":"Business","award":"Saver","price":25000},
{"from":"Carrib.","to":"US, AK, Can","cabin":"Business","award":"Saver","price":30000},
{"from":"Carrib.","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"Carrib.","to":"Panama","cabin":"Business","award":"Standard","price":40000},
{"from":"Carrib.","to":"Carrib.","cabin":"Business","award":"Standard","price":45000},
{"from":"Carrib.","to":"Colom.","cabin":"Business","award":"Standard","price":45000},
{"from":"Carrib.","to":"N. S Amer.","cabin":"Business","award":"Standard","price":45000},
{"from":"Carrib.","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"Carrib.","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Carrib.","to":"Mexico","cabin":"Business","award":"Standard","price":50000},
{"from":"Carrib.","to":"US, AK, Can","cabin":"Business","award":"Standard","price":70000},
{"from":"Cent. Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":7500},
{"from":"Cent. Amer.","to":"Carrib.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Cent. Amer.","to":"Colom.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Cent. Amer.","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Cent. Amer.","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":15000},
{"from":"Cent. Amer.","to":"Panama","cabin":"Economy","award":"Saver","price":7500},
{"from":"Cent. Amer.","to":"Mexico","cabin":"Economy","award":"Saver","price":10000},
{"from":"Cent. Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":15000},
{"from":"Cent. Amer.","to":"Carrib.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Cent. Amer.","to":"Colom.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Cent. Amer.","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Cent. Amer.","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"Cent. Amer.","to":"Panama","cabin":"Economy","award":"Standard","price":15000},
{"from":"Cent. Amer.","to":"Mexico","cabin":"Economy","award":"Standard","price":20000},
{"from":"Cent. Amer.","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"Carrib.","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"Colom.","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"N. S Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"Cent. Amer.","to":"Panama","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"US, AK, Can","cabin":"Business","award":"Saver","price":30000},
{"from":"Cent. Amer.","to":"Mexico","cabin":"Business","award":"Saver","price":20000},
{"from":"Cent. Amer.","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"Carrib.","cabin":"Business","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"Colom.","cabin":"Business","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"N. S Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"Cent. Amer.","to":"Panama","cabin":"Business","award":"Standard","price":40000},
{"from":"Cent. Amer.","to":"US, AK, Can","cabin":"Business","award":"Standard","price":70000},
{"from":"Cent. Amer.","to":"Mexico","cabin":"Business","award":"Standard","price":40000},
{"from":"Colom.","to":"Colom.","cabin":"Economy","award":"Saver","price":5000},
{"from":"Colom.","to":"Carrib.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Colom.","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Colom.","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":7500},
{"from":"Colom.","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":15000},
{"from":"Colom.","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"Colom.","to":"Panama","cabin":"Economy","award":"Saver","price":7500},
{"from":"Colom.","to":"Mexico","cabin":"Economy","award":"Saver","price":10000},
{"from":"Colom.","to":"Colom.","cabin":"Economy","award":"Standard","price":10000},
{"from":"Colom.","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":15000},
{"from":"Colom.","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"Colom.","to":"Panama","cabin":"Economy","award":"Standard","price":15000},
{"from":"Colom.","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"Colom.","to":"Carrib.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Colom.","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Colom.","to":"Mexico","cabin":"Economy","award":"Standard","price":20000},
{"from":"Colom.","to":"Colom.","cabin":"Business","award":"Saver","price":20000},
{"from":"Colom.","to":"N. S Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Colom.","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"Colom.","to":"Panama","cabin":"Business","award":"Saver","price":20000},
{"from":"Colom.","to":"US, AK, Can","cabin":"Business","award":"Saver","price":35000},
{"from":"Colom.","to":"Carrib.","cabin":"Business","award":"Saver","price":25000},
{"from":"Colom.","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Colom.","to":"Mexico","cabin":"Business","award":"Saver","price":20000},
{"from":"Colom.","to":"Colom.","cabin":"Business","award":"Standard","price":40000},
{"from":"Colom.","to":"N. S Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Colom.","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"Colom.","to":"Panama","cabin":"Business","award":"Standard","price":40000},
{"from":"Colom.","to":"US, AK, Can","cabin":"Business","award":"Standard","price":75000},
{"from":"Colom.","to":"Carrib.","cabin":"Business","award":"Standard","price":45000},
{"from":"Colom.","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Colom.","to":"Mexico","cabin":"Business","award":"Standard","price":40000},
{"from":"Mexico","to":"Panama","cabin":"Economy","award":"Saver","price":10000},
{"from":"Mexico","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Mexico","to":"Carrib.","cabin":"Economy","award":"Saver","price":12500},
{"from":"Mexico","to":"Colom.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Mexico","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":12500},
{"from":"Mexico","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"Mexico","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":17500},
{"from":"Mexico","to":"Panama","cabin":"Economy","award":"Standard","price":20000},
{"from":"Mexico","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Mexico","to":"Carrib.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Mexico","to":"Colom.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Mexico","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":25000},
{"from":"Mexico","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"Mexico","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"Mexico","to":"Panama","cabin":"Business","award":"Saver","price":20000},
{"from":"Mexico","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Mexico","to":"Carrib.","cabin":"Business","award":"Saver","price":25000},
{"from":"Mexico","to":"Colom.","cabin":"Business","award":"Saver","price":20000},
{"from":"Mexico","to":"N. S Amer.","cabin":"Business","award":"Saver","price":25000},
{"from":"Mexico","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"Mexico","to":"US, AK, Can","cabin":"Business","award":"Saver","price":30000},
{"from":"Mexico","to":"Panama","cabin":"Business","award":"Standard","price":40000},
{"from":"Mexico","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Mexico","to":"Carrib.","cabin":"Business","award":"Standard","price":50000},
{"from":"Mexico","to":"Colom.","cabin":"Business","award":"Standard","price":40000},
{"from":"Mexico","to":"N. S Amer.","cabin":"Business","award":"Standard","price":50000},
{"from":"Mexico","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"Mexico","to":"US, AK, Can","cabin":"Business","award":"Standard","price":70000},
{"from":"N. S Amer.","to":"Panama","cabin":"Economy","award":"Saver","price":10000},
{"from":"N. S Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"N. S Amer.","to":"Carrib.","cabin":"Economy","award":"Saver","price":10000},
{"from":"N. S Amer.","to":"Mexico","cabin":"Economy","award":"Saver","price":12500},
{"from":"N. S Amer.","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"N. S Amer.","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":15000},
{"from":"N. S Amer.","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"N. S Amer.","to":"Colom.","cabin":"Economy","award":"Saver","price":7500},
{"from":"N. S Amer.","to":"Panama","cabin":"Economy","award":"Standard","price":20000},
{"from":"N. S Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"N. S Amer.","to":"Carrib.","cabin":"Economy","award":"Standard","price":25000},
{"from":"N. S Amer.","to":"Mexico","cabin":"Economy","award":"Standard","price":25000},
{"from":"N. S Amer.","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":15000},
{"from":"N. S Amer.","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"N. S Amer.","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"N. S Amer.","to":"Colom.","cabin":"Economy","award":"Standard","price":15000},
{"from":"N. S Amer.","to":"Panama","cabin":"Business","award":"Saver","price":20000},
{"from":"N. S Amer.","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"N. S Amer.","to":"Carrib.","cabin":"Business","award":"Saver","price":25000},
{"from":"N. S Amer.","to":"Mexico","cabin":"Business","award":"Saver","price":25000},
{"from":"N. S Amer.","to":"N. S Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"N. S Amer.","to":"US, AK, Can","cabin":"Business","award":"Saver","price":35000},
{"from":"N. S Amer.","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"N. S Amer.","to":"Colom.","cabin":"Business","award":"Saver","price":20000},
{"from":"N. S Amer.","to":"Panama","cabin":"Business","award":"Standard","price":40000},
{"from":"N. S Amer.","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"N. S Amer.","to":"Carrib.","cabin":"Business","award":"Standard","price":45000},
{"from":"N. S Amer.","to":"Mexico","cabin":"Business","award":"Standard","price":50000},
{"from":"N. S Amer.","to":"N. S Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"N. S Amer.","to":"US, AK, Can","cabin":"Business","award":"Standard","price":80000},
{"from":"N. S Amer.","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"N. S Amer.","to":"Colom.","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"Panama","cabin":"Economy","award":"Saver","price":5000},
{"from":"Panama","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":7500},
{"from":"Panama","to":"Carrib.","cabin":"Economy","award":"Saver","price":7500},
{"from":"Panama","to":"Colom.","cabin":"Economy","award":"Saver","price":7500},
{"from":"Panama","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":10000},
{"from":"Panama","to":"Mexico","cabin":"Economy","award":"Saver","price":10000},
{"from":"Panama","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"Panama","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":15000},
{"from":"Panama","to":"Panama","cabin":"Economy","award":"Standard","price":10000},
{"from":"Panama","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":15000},
{"from":"Panama","to":"Carrib.","cabin":"Economy","award":"Standard","price":15000},
{"from":"Panama","to":"Colom.","cabin":"Economy","award":"Standard","price":15000},
{"from":"Panama","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":20000},
{"from":"Panama","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"Panama","to":"Mexico","cabin":"Economy","award":"Standard","price":20000},
{"from":"Panama","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":30000},
{"from":"Panama","to":"Panama","cabin":"Business","award":"Saver","price":10000},
{"from":"Panama","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Panama","to":"Carrib.","cabin":"Business","award":"Saver","price":20000},
{"from":"Panama","to":"Colom.","cabin":"Business","award":"Saver","price":20000},
{"from":"Panama","to":"N. S Amer.","cabin":"Business","award":"Saver","price":20000},
{"from":"Panama","to":"South S. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"Panama","to":"Mexico","cabin":"Business","award":"Saver","price":20000},
{"from":"Panama","to":"US, AK, Can","cabin":"Business","award":"Saver","price":30000},
{"from":"Panama","to":"Panama","cabin":"Business","award":"Standard","price":15000},
{"from":"Panama","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"Carrib.","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"Colom.","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"N. S Amer.","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"South S. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"Panama","to":"Mexico","cabin":"Business","award":"Standard","price":40000},
{"from":"Panama","to":"US, AK, Can","cabin":"Business","award":"Standard","price":70000},
{"from":"South S. Amer.","to":"US, AK, Can","cabin":"Economy","award":"Saver","price":25000},
{"from":"South S. Amer.","to":"Mexico","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"Panama","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"Carrib.","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"Colom.","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":20000},
{"from":"South S. Amer.","to":"US, AK, Can","cabin":"Economy","award":"Standard","price":50000},
{"from":"South S. Amer.","to":"Mexico","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"Panama","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"Carrib.","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"Colom.","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":40000},
{"from":"South S. Amer.","to":"Mexico","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"Panama","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"Carrib.","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"Colom.","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"N. S Amer.","cabin":"Business","award":"Saver","price":40000},
{"from":"South S. Amer.","to":"US, AK, Can","cabin":"Business","award":"Saver","price":55000},
{"from":"South S. Amer.","to":"Mexico","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"Panama","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"Carrib.","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"Colom.","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"N. S Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"South S. Amer.","to":"US, AK, Can","cabin":"Business","award":"Standard","price":120000},
{"from":"US, AK, Can","to":"Mexico","cabin":"Economy","award":"Saver","price":17500},
{"from":"US, AK, Can","to":"Panama","cabin":"Economy","award":"Saver","price":15000},
{"from":"US, AK, Can","to":"Cent. Amer.","cabin":"Economy","award":"Saver","price":15000},
{"from":"US, AK, Can","to":"Carrib.","cabin":"Economy","award":"Saver","price":15000},
{"from":"US, AK, Can","to":"Colom.","cabin":"Economy","award":"Saver","price":15000},
{"from":"US, AK, Can","to":"N. S Amer.","cabin":"Economy","award":"Saver","price":15000},
{"from":"US, AK, Can","to":"South S. Amer.","cabin":"Economy","award":"Saver","price":25000},
{"from":"US, AK, Can","to":"Mexico","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"Panama","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"Cent. Amer.","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"Carrib.","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"Colom.","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"N. S Amer.","cabin":"Economy","award":"Standard","price":30000},
{"from":"US, AK, Can","to":"South S. Amer.","cabin":"Economy","award":"Standard","price":50000},
{"from":"US, AK, Can","to":"Mexico","cabin":"Business","award":"Saver","price":30000},
{"from":"US, AK, Can","to":"Panama","cabin":"Business","award":"Saver","price":30000},
{"from":"US, AK, Can","to":"Cent. Amer.","cabin":"Business","award":"Saver","price":30000},
{"from":"US, AK, Can","to":"Carrib.","cabin":"Business","award":"Saver","price":30000},
{"from":"US, AK, Can","to":"Colom.","cabin":"Business","award":"Saver","price":35000},
{"from":"US, AK, Can","to":"N. S Amer.","cabin":"Business","award":"Saver","price":35000},
{"from":"US, AK, Can","to":"South S. Amer.","cabin":"Business","award":"Saver","price":55000},
{"from":"US, AK, Can","to":"Mexico","cabin":"Business","award":"Standard","price":70000},
{"from":"US, AK, Can","to":"Panama","cabin":"Business","award":"Standard","price":70000},
{"from":"US, AK, Can","to":"Cent. Amer.","cabin":"Business","award":"Standard","price":70000},
{"from":"US, AK, Can","to":"Carrib.","cabin":"Business","award":"Standard","price":70000},
{"from":"US, AK, Can","to":"Colom.","cabin":"Business","award":"Standard","price":75000},
{"from":"US, AK, Can","to":"N. S Amer.","cabin":"Business","award":"Standard","price":80000},
{"from":"US, AK, Can","to":"South S. Amer.","cabin":"Business","award":"Standard","price":120000}]


var citySegmentsBuscadorCaminos =
  [{"cities": ["MDE", "BOG"], mileage: "134"},
    {"cities": ["BOG", "MDE"], mileage: "134"},
    {"cities": ["CLO", "BOG"], mileage: "174"},
    {"cities": ["BOG", "CLO"], mileage: "174"},
    {"cities": ["PTY", "CTG"], mileage: "280"},
    {"cities": ["CTG", "PTY"], mileage: "280"},
    {"cities": ["PTY", "ADZ"], mileage: "289"},
    {"cities": ["ADZ", "PTY"], mileage: "289"},
    {"cities": ["PTY", "SJO"], mileage: "335"},
    {"cities": ["SJO", "PTY"], mileage: "335"},
    {"cities": ["MDE", "PTY"], mileage: "337"},
    {"cities": ["PTY", "MDE"], mileage: "337"},
    {"cities": ["BAQ", "PTY"], mileage: "338"},
    {"cities": ["PTY", "BAQ"], mileage: "338"},
    {"cities": ["PEI", "PTY"], mileage: "385"},
    {"cities": ["PTY", "PEI"], mileage: "385"},
    {"cities": ["CLO", "PTY"], mileage: "432"},
    {"cities": ["PTY", "CLO"], mileage: "432"},
    {"cities": ["BGA", "PTY"], mileage: "445"},
    {"cities": ["PTY", "BGA"], mileage: "445"},
    {"cities": ["CTG", "ADZ"], mileage: "445"},
    {"cities": ["ADZ", "CTG"], mileage: "445"},
    {"cities": ["UIO", "BOG"], mileage: "448"},
    {"cities": ["BOG", "UIO"], mileage: "448"},
    {"cities": ["PTY", "BOG"], mileage: "469"},
    {"cities": ["BOG", "PTY"], mileage: "469"},
    {"cities": ["PTY", "CUC"], mileage: "476"},
    {"cities": ["CUC", "PTY"], mileage: "476"},
    {"cities": ["BAQ", "ADZ"], mileage: "484"},
    {"cities": ["ADZ", "BAQ"], mileage: "484"},
    {"cities": ["SJO", "GUA"], mileage: "531"},
    {"cities": ["GUA", "SJO"], mileage: "531"},
    {"cities": ["PTY", "UIO"], mileage: "636"},
    {"cities": ["UIO", "PTY"], mileage: "636"},
    {"cities": ["CCS", "BOG"], mileage: "636"},
    {"cities": ["BOG", "CCS"], mileage: "636"},
    {"cities": ["PEI", "ADZ"], mileage: "672"},
    {"cities": ["ADZ", "PEI"], mileage: "672"},
    {"cities": ["CLO", "ADZ"], mileage: "720"},
    {"cities": ["ADZ", "CLO"], mileage: "720"},
    {"cities": ["PTY", "SAP"], mileage: "725"},
    {"cities": ["SAP", "PTY"], mileage: "725"},
    {"cities": ["BOG", "ADZ"], mileage: "749"},
    {"cities": ["ADZ", "BOG"], mileage: "749"},
    {"cities": ["PTY", "GYE"], mileage: "772"},
    {"cities": ["GYE", "PTY"], mileage: "772"},
    {"cities": ["PTY", "STI"], mileage: "922"},
    {"cities": ["STI", "PTY"], mileage: "922"},
    {"cities": ["PTY", "PUJ"], mileage: "986"},
    {"cities": ["PUJ", "PTY"], mileage: "986"},
    {"cities": ["BOG", "PUJ"], mileage: "1030"},
    {"cities": ["PUJ", "BOG"], mileage: "1030"},
    {"cities": ["BOG", "HAV"], mileage: "1373"},
    {"cities": ["HAV", "BOG"], mileage: "1373"},
    {"cities": ["BOG", "CUN"], mileage: "1412"},
    {"cities": ["CUN", "BOG"], mileage: "1412"},
    {"cities": ["BOG", "MEX"], mileage: "1962"},
    {"cities": ["MEX", "BOG"], mileage: "1962"},
    {"cities": ["PTY", "MSY"], mileage: "1602"},
    {"cities": ["MSY", "PTY"], mileage: "1602"},
    {"cities": ["PTY", "SFO"], mileage: "3320"},
    {"cities": ["SFO", "PTY"], mileage: "3320"},
    {"cities": ["PTY", "VSA"], mileage: "1091"},
    {"cities": ["VSA", "PTY"], mileage: "1091"},
    {"cities": ["PTY", "PBC"], mileage: "1448"},
    {"cities": ["PBC", "PTY"], mileage: "1448"},
    {"cities": ["PTY", "AUA"], mileage: "679"},
    {"cities": ["AUA", "PTY"], mileage: "679"},
    {"cities": ["BSB", "PTY"], mileage: "2754"},
    {"cities": ["PTY", "BSB"], mileage: "2754"},
    {"cities": ["CCS", "PTY"], mileage: "851"},
    {"cities": ["PTY", "CCS"], mileage: "851"},
    {"cities": ["CNF", "PTY"], mileage: "3116"},
    {"cities": ["PTY", "CNF"], mileage: "3116"},
    {"cities": ["COR", "PTY"], mileage: "2954"},
    {"cities": ["PTY", "COR"], mileage: "2954"},
    {"cities": ["PTY", "CUN"], mileage: "962"},
    {"cities": ["CUN", "PTY"], mileage: "962"},
    {"cities": ["EZE", "PTY"], mileage: "3313"},
    {"cities": ["PTY", "EZE"], mileage: "3313"},
    {"cities": ["GDL", "PTY"], mileage: "1780"},
    {"cities": ["PTY", "GDL"], mileage: "1780"},
    {"cities": ["GIG", "PTY"], mileage: "3285"},
    {"cities": ["PTY", "GIG"], mileage: "3285"},
    {"cities": ["GRU", "PTY"], mileage: "3154"},
    {"cities": ["PTY", "GRU"], mileage: "3154"},
    {"cities": ["PTY", "GUA"], mileage: "844"},
    {"cities": ["GUA", "PTY"], mileage: "844"},
    {"cities": ["PTY", "HAV"], mileage: "978"},
    {"cities": ["HAV", "PTY"], mileage: "978"},
    {"cities": ["IAD", "PTY"], mileage: "2060"},
    {"cities": ["PTY", "IAD"], mileage: "2060"},
    {"cities": ["JFK", "PTY"], mileage: "2200"},
    {"cities": ["PTY", "JFK"], mileage: "2200"},
    {"cities": ["PTY", "KIN"], mileage: "634"},
    {"cities": ["KIN", "PTY"], mileage: "634"},
    {"cities": ["PTY", "LAX"], mileage: "3010"},
    {"cities": ["LAX", "PTY"], mileage: "3010"},
    {"cities": ["LIM", "PTY"], mileage: "1458"},
    {"cities": ["PTY", "LIM"], mileage: "1458"},
    {"cities": ["MAO", "PTY"], mileage: "1571"},
    {"cities": ["PTY", "MAO"], mileage: "1571"},
    {"cities": ["MCO", "PTY"], mileage: "1337"},
    {"cities": ["PTY", "MCO"], mileage: "1337"},
    {"cities": ["PTY", "MEX"], mileage: "1498"},
    {"cities": ["MEX", "PTY"], mileage: "1498"},
    {"cities": ["PTY", "MGA"], mileage: "507"},
    {"cities": ["MGA", "PTY"], mileage: "507"},
    {"cities": ["PTY", "MIA"], mileage: "1152"},
    {"cities": ["MIA", "PTY"], mileage: "1152"},
    {"cities": ["MVD", "PTY"], mileage: "3385"},
    {"cities": ["PTY", "MVD"], mileage: "3385"},
    {"cities": ["PTY", "PAP"], mileage: "808"},
    {"cities": ["PAP", "PTY"], mileage: "808"},
    {"cities": ["PTY", "POS"], mileage: "1234"},
    {"cities": ["POS", "PTY"], mileage: "1234"},
    {"cities": ["PTY", "SAL"], mileage: "722"},
    {"cities": ["SAL", "PTY"], mileage: "722"},
    {"cities": ["PTY", "SCL"], mileage: "2974"},
    {"cities": ["SCL", "PTY"], mileage: "2974"},
    {"cities": ["PTY", "SDQ"], mileage: "916"},
    {"cities": ["SDQ", "PTY"], mileage: "916"},
    {"cities": ["PTY", "SJU"], mileage: "1105"},
    {"cities": ["SJU", "PTY"], mileage: "1105"},
    {"cities": ["PTY", "SXM"], mileage: "1255"},
    {"cities": ["SXM", "PTY"], mileage: "1255"},
    {"cities": ["PTY", "VLN"], mileage: "785"},
    {"cities": ["VLN", "PTY"], mileage: "785"},
    {"cities": ["PTY", "VVI"], mileage: "2146"},
    {"cities": ["VVI", "PTY"], mileage: "2146"},
    {"cities": ["PTY", "YYZ"], mileage: "2383"},
    {"cities": ["YYZ", "PTY"], mileage: "2383"},
    {"cities": ["MGA", "GUA"], mileage: "338"},
    {"cities": ["SJO", "SAP"], mileage: "451"},
    {"cities": ["SAP", "SJO"], mileage: "451"},
    {"cities": ["SJO", "TGU"], mileage: "346"},
    {"cities": ["TGU", "PTY"], mileage: "632"},
    {"cities": ["PTY", "TGU"], mileage: "632"},
    {"cities": ["TGU", "SJO"], mileage: "346"},
    {"cities": ["PTY", "MBJ"], mileage: "656"},
    {"cities": ["MBJ", "PTY"], mileage: "656"},
    {"cities": ["ASU", "PTY"], mileage: "2781"},
    {"cities": ["PTY", "ASU"], mileage: "2781"},
    {"cities": ["PTY", "ORD"], mileage: "2325"},
    {"cities": ["ORD", "PTY"], mileage: "2325"},
    {"cities": ["MGA", "SJO"], mileage: "199"},
    {"cities": ["SJO", "MGA"], mileage: "199"},
    {"cities": ["PTY", "LAS"], mileage: "2916"},
    {"cities": ["LAS", "PTY"], mileage: "2916"},
    {"cities": ["PTY", "CUR"], mileage: "740"},
    {"cities": ["CUR", "PTY"], mileage: "740"},
    {"cities": ["PTY", "LIR"], mileage: "433"},
    {"cities": ["LIR", "PTY"], mileage: "433"},
    {"cities": ["IQT", "PTY"], mileage: "978"},
    {"cities": ["PTY", "IQT"], mileage: "978"},
    {"cities": ["POA", "PTY"], mileage: "3277"},
    {"cities": ["PTY", "POA"], mileage: "3277"},
    {"cities": ["PTY", "NAS"], mileage: "1105"},
    {"cities": ["NAS", "PTY"], mileage: "1105"},
    {"cities": ["PTY", "MTY"], mileage: "1781"},
    {"cities": ["MTY", "PTY"], mileage: "1781"},
    {"cities": ["PTY", "BOS"], mileage: "2348"},
    {"cities": ["BOS", "PTY"], mileage: "2348"},
    {"cities": ["PTY", "TPA"], mileage: "1316"},
    {"cities": ["TPA", "PTY"], mileage: "1316"},
    {"cities": ["PTY", "YUL"], mileage: "2529"},
    {"cities": ["YUL", "PTY"], mileage: "2529"},
    {"cities": ["PTY", "GEO"], mileage: "1459"},
    {"cities": ["GEO", "PTY"], mileage: "1459"},
    {"cities": ["PTY", "FLL"], mileage: "1170"},
    {"cities": ["FLL", "PTY"], mileage: "1170"},
    {"cities": ["PTY", "SNU"], mileage: "924"},
    {"cities": ["SNU", "PTY"], mileage: "924"},
    {"cities": ["PTY", "MAR"], mileage: "532"},
    {"cities": ["MAR", "PTY"], mileage: "532"},
    {"cities": ["GUA", "MGA"], mileage: "338"},
    {"cities": ["PTY", "VCP"], mileage: "3103"},
    {"cities": ["VCP", "PTY"], mileage: "3103"},
    {"cities": ["PTY", "DAV"], mileage: "214"},
    {"cities": ["DAV", "PTY"], mileage: "214"},
    {"cities": ["PTY", "REC"], mileage: "3284"},
    {"cities": ["REC", "PTY"], mileage: "3284"}];


var citySegments =  [
  { cities: ["SFO","PTY"], distance:3320, "mileages": [] },
  { cities: ["PTY","MSY"], distance:1602, "mileages": [] },
  { cities: ["MSY","PTY"], distance:1602, "mileages": [] },
  { cities: ["PTY","PBC"], distance:1448, "mileages": [] },
  { cities: ["PBC","PTY"], distance:1448, "mileages": [] },
  { cities: ["PTY","VSA"], distance:1091, "mileages": [] },
  { cities: ["VSA","PTY"], distance:1091, "mileages": [] },
  { cities: ["PTY","SNU"], distance:924, "mileages": [] },
  { cities: ["SNU","PTY"], distance:924, "mileages": [] },
  { cities: ["PTY","VCP"], distance:3103, "mileages": [] },
  { cities: ["VCP","PTY"], distance:3103, "mileages": [] },
  { cities: ["PTY","DAV"], distance:214, "mileages": [] },
  { cities: ["DAV","PTY"], distance:214, "mileages": [] },
  { cities: ["MVD","PTY"], distance:3396, "mileages": [] },
  { cities: ["PTY","MVD"], distance:3396, "mileages": [] },
  { cities: ["EZE","PTY"], distance:3318, "mileages": [] },
  { cities: ["PTY","EZE"], distance:3318, "mileages": [] },
  { cities: ["GIG","PTY"], distance:3297, "mileages": [] },
  { cities: ["PTY","GIG"], distance:3297, "mileages": [] },
  { cities: ["POA","PTY"], distance:3287, "mileages": [] },
  { cities: ["PTY","POA"], distance:3287, "mileages": [] },
  { cities: ["PTY","REC"], distance:3284, "mileages": [] },
  { cities: ["REC","PTY"], distance:3284, "mileages": [] },
  { cities: ["GRU","PTY"], distance:3145, "mileages": [] },
  { cities: ["PTY","GRU"], distance:3145, "mileages": [] },
  { cities: ["CNF","PTY"], distance:3129, "mileages": [] },
  { cities: ["PTY","CNF"], distance:3129, "mileages": [] },
  { cities: ["PTY","LAX"], distance:3009, "mileages": [] },
  { cities: ["LAX","PTY"], distance:3009, "mileages": [] },
  { cities: ["SCL","PTY"], distance:2986, "mileages": [] },
  { cities: ["PTY","SCL"], distance:2986, "mileages": [] },
  { cities: ["COR","PTY"], distance:2965, "mileages": [] },
  { cities: ["PTY","COR"], distance:2965, "mileages": [] },
  { cities: ["PTY","LAS"], distance:2916, "mileages": [] },
  { cities: ["LAS","PTY"], distance:2916, "mileages": [] },
  { cities: ["ASU","PTY"], distance:2791, "mileages": [] },
  { cities: ["PTY","ASU"], distance:2791, "mileages": [] },
  { cities: ["BSB","PTY"], distance:2759, "mileages": [] },
  { cities: ["PTY","BSB"], distance:2759, "mileages": [] },
  { cities: ["PTY","YUL"], distance:2529, "mileages": [] },
  { cities: ["YUL","PTY"], distance:2529, "mileages": [] },
  { cities: ["PTY","YYZ"], distance:2384, "mileages": [] },
  { cities: ["YYZ","PTY"], distance:2384, "mileages": [] },
  { cities: ["PTY","BOS"], distance:2348, "mileages": [] },
  { cities: ["BOS","PTY"], distance:2348, "mileages": [] },
  { cities: ["PTY","ORD"], distance:2330, "mileages": [] },
  { cities: ["ORD","PTY"], distance:2330, "mileages": [] },
  { cities: ["JFK","PTY"], distance:2216, "mileages": [] },
  { cities: ["PTY","JFK"], distance:2216, "mileages": [] },
  { cities: ["PTY","VVI"], distance:2153, "mileages": [] },
  { cities: ["VVI","PTY"], distance:2153, "mileages": [] },
  { cities: ["IAD","PTY"], distance:2070, "mileages": [] },
  { cities: ["PTY","IAD"], distance:2070, "mileages": [] },
  { cities: ["BOG","MEX"], distance:1976, "mileages": [] },
  { cities: ["MEX","BOG"], distance:1976, "mileages": [] },
  { cities: ["PTY","MTY"], distance:1781, "mileages": [] },
  { cities: ["MTY","PTY"], distance:1781, "mileages": [] },
  { cities: ["GDL","PTY"], distance:1777, "mileages": [] },
  { cities: ["PTY","GDL"], distance:1777, "mileages": [] },
  { cities: ["MAO","PTY"], distance:1584, "mileages": [] },
  { cities: ["PTY","MAO"], distance:1584, "mileages": [] },
  { cities: ["PTY","MEX"], distance:1508, "mileages": [] },
  { cities: ["MEX","PTY"], distance:1508, "mileages": [] },
  { cities: ["LIM","PTY"], distance:1466, "mileages": [] },
  { cities: ["PTY","LIM"], distance:1466, "mileages": [] },
  { cities: ["PTY","GEO"], distance:1459, "mileages": [] },
  { cities: ["GEO","PTY"], distance:1459, "mileages": [] },
  { cities: ["BOG","CUN"], distance:1412, "mileages": [] },
  { cities: ["CUN","BOG"], distance:1412, "mileages": [] },
  { cities: ["BOG","HAV"], distance:1380, "mileages": [] },
  { cities: ["HAV","BOG"], distance:1380, "mileages": [] },
  { cities: ["MCO","PTY"], distance:1356, "mileages": [] },
  { cities: ["PTY","MCO"], distance:1356, "mileages": [] },
  { cities: ["PTY","TPA"], distance:1316, "mileages": [] },
  { cities: ["TPA","PTY"], distance:1316, "mileages": [] },
  { cities: ["PTY","SXM"], distance:1263, "mileages": [] },
  { cities: ["SXM","PTY"], distance:1263, "mileages": [] },
  { cities: ["PTY","POS"], distance:1239, "mileages": [] },
  { cities: ["POS","PTY"], distance:1239, "mileages": [] },
  { cities: ["PTY","FLL"], distance:1170, "mileages": [] },
  { cities: ["FLL","PTY"], distance:1170, "mileages": [] },
  { cities: ["PTY","MIA"], distance:1161, "mileages": [] },
  { cities: ["MIA","PTY"], distance:1161, "mileages": [] },
  { cities: ["PTY","NAS"], distance:1116, "mileages": [] },
  { cities: ["NAS","PTY"], distance:1116, "mileages": [] },
  { cities: ["PTY","SJU"], distance:1111, "mileages": [] },
  { cities: ["SJU","PTY"], distance:1111, "mileages": [] },
  { cities: ["BOG","PUJ"], distance:1030, "mileages": [] },
  { cities: ["PUJ","BOG"], distance:1030, "mileages": [] },
  { cities: ["PTY","PUJ"], distance:994, "mileages": [] },
  { cities: ["PUJ","PTY"], distance:994, "mileages": [] },
  { cities: ["PTY","HAV"], distance:987, "mileages": [] },
  { cities: ["HAV","PTY"], distance:987, "mileages": [] },
  { cities: ["IQT","PTY"], distance:978, "mileages": [] },
  { cities: ["PTY","IQT"], distance:978, "mileages": [] },
  { cities: ["PTY","CUN"], distance:973, "mileages": [] },
  { cities: ["CUN","PTY"], distance:973, "mileages": [] },
  { cities: ["PTY","STI"], distance:929, "mileages": [] },
  { cities: ["STI","PTY"], distance:929, "mileages": [] },
  { cities: ["PTY","SDQ"], distance:925, "mileages": [] },
  { cities: ["SDQ","PTY"], distance:925, "mileages": [] },
  { cities: ["CCS","PTY"], distance:859, "mileages": [] },
  { cities: ["PTY","CCS"], distance:859, "mileages": [] },
  { cities: ["PTY","GUA"], distance:841, "mileages": [] },
  { cities: ["GUA","PTY"], distance:841, "mileages": [] },
  { cities: ["PTY","PAP"], distance:814, "mileages": [] },
  { cities: ["PAP","PTY"], distance:814, "mileages": [] },
  { cities: ["PTY","VLN"], distance:790, "mileages": [] },
  { cities: ["VLN","PTY"], distance:790, "mileages": [] },
  { cities: ["PTY","GYE"], distance:774, "mileages": [] },
  { cities: ["GYE","PTY"], distance:774, "mileages": [] },
  { cities: ["BOG","ADZ"], distance:749, "mileages": [] },
  { cities: ["ADZ","BOG"], distance:749, "mileages": [] },
  { cities: ["PTY","SAP"], distance:744, "mileages": [] },
  { cities: ["SAP","PTY"], distance:744, "mileages": [] },
  { cities: ["PTY","CUR"], distance:740, "mileages": [] },
  { cities: ["CUR","PTY"], distance:740, "mileages": [] },
  { cities: ["PTY","SAL"], distance:730, "mileages": [] },
  { cities: ["SAL","PTY"], distance:730, "mileages": [] },
  { cities: ["CLO","ADZ"], distance:728, "mileages": [] },
  { cities: ["ADZ","CLO"], distance:728, "mileages": [] },
  { cities: ["PTY","AUA"], distance:686, "mileages": [] },
  { cities: ["AUA","PTY"], distance:686, "mileages": [] },
  { cities: ["TGU","PTY"], distance:678, "mileages": [] },
  { cities: ["PTY","TGU"], distance:678, "mileages": [] },
  { cities: ["ADZ","PEI"], distance:672, "mileages": [] },
  { cities: ["PEI","ADZ"], distance:672, "mileages": [] },
  { cities: ["PTY","MBJ"], distance:665, "mileages": [] },
  { cities: ["MBJ","PTY"], distance:665, "mileages": [] },
  { cities: ["MDE","CCS"], distance:664, "mileages": [] },
  { cities: ["CCS","MDE"], distance:664, "mileages": [] },
  { cities: ["PTY","KIN"], distance:644, "mileages": [] },
  { cities: ["KIN","PTY"], distance:644, "mileages": [] },
  { cities: ["BOG","CCS"], distance:638, "mileages": [] },
  { cities: ["CCS","BOG"], distance:638, "mileages": [] },
  { cities: ["PTY","UIO"], distance:636, "mileages": [] },
  { cities: ["UIO","PTY"], distance:636, "mileages": [] },
  { cities: ["MDE","ADZ"], distance:605, "mileages": [] },
  { cities: ["ADZ","MDE"], distance:605, "mileages": [] },
  { cities: ["MAR","PTY"], distance:546, "mileages": [] },
  { cities: ["PTY","MAR"], distance:546, "mileages": [] },
  { cities: ["SJO","GUA"], distance:532, "mileages": [] },
  { cities: ["GUA","SJO"], distance:532, "mileages": [] },
  { cities: ["PTY","MGA"], distance:504, "mileages": [] },
  { cities: ["MGA","PTY"], distance:504, "mileages": [] },
  { cities: ["BAQ","ADZ"], distance:482, "mileages": [] },
  { cities: ["ADZ","BAQ"], distance:482, "mileages": [] },
  { cities: ["PTY","CUC"], distance:481, "mileages": [] },
  { cities: ["CUC","PTY"], distance:481, "mileages": [] },
  { cities: ["PTY","BOG"], distance:472, "mileages": [] },
  { cities: ["BOG","PTY"], distance:472, "mileages": [] },
  { cities: ["SJO","SAP"], distance:460, "mileages": [] },
  { cities: ["SAP","SJO"], distance:460, "mileages": [] },
  { cities: ["BGA","PTY"], distance:453, "mileages": [] },
  { cities: ["PTY","BGA"], distance:453, "mileages": [] },
  { cities: ["UIO","BOG"], distance:450, "mileages": [] },
  { cities: ["BOG","UIO"], distance:450, "mileages": [] },
  { cities: ["CTG","ADZ"], distance:443, "mileages": [] },
  { cities: ["ADZ","CTG"], distance:443, "mileages": [] },
  { cities: ["CLO","PTY"], distance:440, "mileages": [] },
  { cities: ["PTY","CLO"], distance:440, "mileages": [] },
  { cities: ["PTY","LIR"], distance:433, "mileages": [] },
  { cities: ["LIR","PTY"], distance:433, "mileages": [] },
  { cities: ["BOG","CTG"], distance:409, "mileages": [] },
  { cities: ["CTG","BOG"], distance:409, "mileages": [] },
  { cities: ["PEI","PTY"], distance:388, "mileages": [] },
  { cities: ["PTY","PEI"], distance:388, "mileages": [] },
  { cities: ["SJO","TGU"], distance:348, "mileages": [] },
  { cities: ["TGU","SJO"], distance:348, "mileages": [] },
  { cities: ["BAQ","PTY"], distance:345, "mileages": [] },
  { cities: ["PTY","BAQ"], distance:345, "mileages": [] },
  { cities: ["GUA","MGA"], distance:338, "mileages": [] },
  { cities: ["MGA","GUA"], distance:338, "mileages": [] },
  { cities: ["PTY","SJO"], distance:330, "mileages": [] },
  { cities: ["SJO","PTY"], distance:330, "mileages": [] },
  { cities: ["MDE","PTY"], distance:329, "mileages": [] },
  { cities: ["PTY","MDE"], distance:329, "mileages": [] },
  { cities: ["CTG","PTY"], distance:288, "mileages": [] },
  { cities: ["PTY","CTG"], distance:288, "mileages": [] },
  { cities: ["PTY","ADZ"], distance:288, "mileages": [] },
  { cities: ["ADZ","PTY"], distance:288, "mileages": [] },
  { cities: ["MGA","SJO"], distance:200, "mileages": [] },
  { cities: ["SJO","MGA"], distance:200, "mileages": [] },
  { cities: ["BGA","BOG"], distance:181, "mileages": [] },
  { cities: ["BOG","BGA"], distance:181, "mileages": [] },
  { cities: ["CLO","BOG"], distance:179, "mileages": [] },
  { cities: ["BOG","CLO"], distance:179, "mileages": [] },
  { cities: ["BOG","MDE"], distance:145, "mileages": [] },
  { cities: ["MDE","BOG"], distance:145, "mileages": [] }
];

var countries = [
  {
    "code": "ADZ",
    "name": "San Andres Island",
    "country": "Colombia",
    "region": "Colom.",
    "latLng": "12.5392437,-81.706956"
  },
  {
    "code": "ASU",
    "name": "Asuncion",
    "country": "Paraguay",
    "region": "South S. Amer.",
    "latLng": "-25.3351612,-57.8839112"
  },
  {"code": "AUA", "name": "Aruba", "country": "Aruba", "region": "Carrib.", "latLng": "12.5183554,-69.9672889"},
  {"code": "BAQ", "name": "Barranquilla", "country": "Colombia", "region": "Colom.", "latLng": "10.992906,-74.8390163"},
  {"code": "BGA", "name": "Bucaramanga", "country": "Colombia", "region": "Colom.", "latLng": "7.1655708,-73.1195478"},
  {"code": "BOG", "name": "Bogota", "country": "Colombia", "region": "Colom.", "latLng": "4.6482975,-74.107807"},
  {
    "code": "BOS",
    "name": "Boston",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "42.3133735,-71.0571571"
  },
  {
    "code": "BSB",
    "name": "Brasilia",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-15.7217621,-47.9382362"
  },
  {"code": "CCS", "name": "Caracas", "country": "Venezuela", "region": "N. S Amer.", "latLng": "10.4683918,-66.8903658"},
  {"code": "CLO", "name": "Cali", "country": "Colombia", "region": "Colom.", "latLng": "3.3950644,-76.525664"},
  {
    "code": "CNF",
    "name": "Belo Horizonte",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-19.9178713,-43.9603116"
  },
  {
    "code": "COR",
    "name": "Cordoba",
    "country": "Argentina",
    "region": "South S. Amer.",
    "latLng": "-31.398639,-64.194344"
  },
  {"code": "CTG", "name": "Cartagena", "country": "Colombia", "region": "Colom.", "latLng": "10.4001987,-75.5085254"},
  {"code": "CUC", "name": "Cucuta", "country": "Colombia", "region": "Colom.", "latLng": "7.90876,-72.5044205"},
  {"code": "CUN", "name": "Cancun", "country": "Mexico", "region": "Mexico", "latLng": "21.1213429,-86.8492333"},
  {"code": "CUR", "name": "Curacao", "country": "Curacao", "region": "Carrib.", "latLng": "12.2136748,-68.9497619"},
  {"code": "DAV", "name": "David", "country": "Panama", "region": "Panama", "latLng": "8.4050165,-82.4270832"},
  {
    "code": "EZE",
    "name": "Buenos Aires Ministro Pistarini",
    "country": "Argentina",
    "region": "South S. Amer.",
    "latLng": "-34.6165989,-58.4429124"
  },
  {
    "code": "FLL",
    "name": "Fort Lauderdale/Hollywood",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "26.1411125,-80.145567"
  },
  {"code": "GDL", "name": "Guadalajara", "country": "Mexico", "region": "Mexico", "latLng": "20.6737919,-103.3354131"},
  {
    "code": "GEO",
    "name": "Georgetown (GY) 00",
    "country": "Guyana",
    "region": "N. S Amer.",
    "latLng": "6.7876283,-58.1515334"
  },
  {
    "code": "GIG",
    "name": "Rio de Janeiro",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-22.9112335,-43.448334"
  },
  {
    "code": "GRU",
    "name": "Sao Paulo Guarulhos",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-23.6824124,-46.5952992"
  },
  {
    "code": "GUA",
    "name": "Guatemala City",
    "country": "Guatemala",
    "region": "Cent. Amer.",
    "latLng": "14.6262201,-90.4925604"
  },
  {"code": "GYE", "name": "Guayaquil", "country": "Ecuador", "region": "N. S Amer.", "latLng": "-2.1523874,-79.9798615"},
  {"code": "HAV", "name": "Havana", "country": "Cuba", "region": "Carrib.", "latLng": "23.0506866,-82.3330021"},
  {
    "code": "IAD",
    "name": "Washington Dulles",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "38.9531162,-77.4565388"
  },
  {"code": "IQT", "name": "Iquitos", "country": "Peru", "region": "N. S Amer.", "latLng": "-3.7529196,-73.2833147"},
  {
    "code": "JFK",
    "name": "New York",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "40.7033127,-73.979681"
  },
  {
    "code": "KIN",
    "name": "Norman Manley Intl",
    "country": "Jamaica",
    "region": "Carrib.",
    "latLng": "18.0179363,-76.8006563"
  },
  {
    "code": "LAS",
    "name": "Las Vegas ",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "36.125,-115.175"
  },
  {
    "code": "LAX",
    "name": "Los Angeles",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "34.020479,-118.4117325"
  },
  {"code": "LIM", "name": "Lima", "country": "Peru", "region": "N. S Amer.", "latLng": "-12.0349126,-77.1508722"},
  {
    "code": "LIR",
    "name": "Liberia",
    "country": "Costa Rica",
    "region": "Cent. Amer.",
    "latLng": "10.6460465,-85.4699311"
  },
  {
    "code": "MAO",
    "name": "Manaus Eduardo Gomes International",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-2.7271474,-59.9894281"
  },
  {
    "code": "MAR",
    "name": "Maracaibo",
    "country": "Venezuela",
    "region": "N. S Amer.",
    "latLng": "10.5711301,-71.6695608"
  },
  {"code": "MBJ", "name": "Montego Bay", "country": "Jamaica", "region": "Carrib.", "latLng": "18.3778407,-77.885938"},
  {
    "code": "MCO",
    "name": "Orlando",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "28.4994104,-81.2924716"
  },
  {
    "code": "MDE",
    "name": "Medellin Jose Maria Cordova Intl",
    "country": "Colombia",
    "region": "Colom.",
    "latLng": "6.631949,-75.9983228"
  },
  {
    "code": "MEX",
    "name": "Mexico City Juarez Intl",
    "country": "Mexico",
    "region": "Mexico",
    "latLng": "19.3573738,-99.1621521"
  },
  {
    "code": "MGA",
    "name": "Managua",
    "country": "Nicaragua",
    "region": "Cent. Amer.",
    "latLng": "12.0849786,-86.2961803"
  },
  {
    "code": "MIA",
    "name": "Miami",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "25.9375955,-80.4657284"
  },
  {
    "code": "MSY",
    "name": "New Orleans",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "30.1462565,-89.6722727"
  },
  {
    "code": "MTY",
    "name": "Monterrey Mariano Escobedo Intl",
    "country": "Mexico",
    "region": "Mexico",
    "latLng": "25.2800844,-100.5258517"
  },
  {
    "code": "MVD",
    "name": "Montevideo",
    "country": "Uruguay",
    "region": "South S. Amer.",
    "latLng": "-34.8210983,-56.2364387"
  },
  {"code": "NAS", "name": "Nassau", "country": "Bahamas", "region": "Carrib.", "latLng": "25.0156984,-77.3977301"},
  {
    "code": "ORD",
    "name": "Chicago O'Hare",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "41.9849227,-87.402323"
  },
  {"code": "PAP", "name": "Port au Prince", "country": "Haiti", "region": "Carrib.", "latLng": "18.6358856,-71.5977652"},
  {"code": "PBC", "name": "Puebla", "country": "Mexico", "region": "Mexico", "latLng": "18.5330463,-98.7105088"},
  {"code": "PEI", "name": "Pereira", "country": "Colombia", "region": "Colom.", "latLng": "4.1993191,-76.3331838"},
  {
    "code": "POA",
    "name": "Porto Alegre",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-30.6160704,-51.8496537"
  },
  {
    "code": "POS",
    "name": "Port of Spain",
    "country": "Trinidad and Tobago",
    "region": "Carrib.",
    "latLng": "10.6272068,-61.8507986"
  },
  {
    "code": "PTY",
    "name": "Panama City Tocumen International",
    "country": "Panama",
    "region": "Panama",
    "latLng": "9.0814152,-79.4531372"
  },
  {
    "code": "PUJ",
    "name": "Punta Cana",
    "country": "Dominican Republic",
    "region": "Carrib.",
    "latLng": "18.8511192,-69.3483014"
  },
  {"code": "REC", "name": "Recife", "country": "Brazil", "region": "South S. Amer.", "latLng": "-7.9397645,-34.8077028"},
  {
    "code": "SAL",
    "name": "San Salvador (SV)",
    "country": "El Salvador",
    "region": "Cent. Amer.",
    "latLng": "13.6935023,-89.2060092"
  },
  {
    "code": "SAP",
    "name": "San Pedro Sula",
    "country": "Honduras",
    "region": "Cent. Amer.",
    "latLng": "15.5009934,-88.7997116"
  },
  {
    "code": "SCL",
    "name": "Santiago (CL)",
    "country": "Chile",
    "region": "South S. Amer.",
    "latLng": "-33.3306669,-70.5121552"
  },
  {
    "code": "SDQ",
    "name": "Santo Domingo Las Americas Intl",
    "country": "Dominican Republic",
    "region": "Carrib.",
    "latLng": "@18.592094,-71.3160727"
  },
  {
    "code": "SFO",
    "name": "San Francisco",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "37.5204547,-122.4142165"
  },
  {
    "code": "SJO",
    "name": "San Jose",
    "country": "Costa Rica",
    "region": "Cent. Amer.",
    "latLng": "9.9356142,-84.1133451"
  },
  {"code": "SJU", "name": "San Juan", "country": "Puerto Rico", "region": "Carrib.", "latLng": "18.1637922,-65.8654184"},
  {"code": "SNU", "name": "Santa Clara", "country": "Cuba", "region": "Carrib.", "latLng": "23.4421909,-81.547002"},
  {
    "code": "STI",
    "name": "Santiago (DO)",
    "country": "Dominican Republic",
    "region": "Carrib.",
    "latLng": "19.1601647,-71.8013325"
  },
  {
    "code": "SXM",
    "name": "St Maarten",
    "country": " St. Maarten",
    "region": "Carrib.",
    "latLng": "18.0527822,-63.1302579"
  },
  {
    "code": "TGU",
    "name": "Tegucigalpa",
    "country": "Honduras",
    "region": "Cent. Amer.",
    "latLng": "14.2626327,-88.5316836"
  },
  {
    "code": "TPA",
    "name": "Tampa",
    "country": "United States",
    "region": "US, AK, Can",
    "latLng": "28.2467114,-82.8629104"
  },
  {"code": "UIO", "name": "Quito", "country": "Ecuador", "region": "N. S Amer.", "latLng": "-0.2010522,-79.2268435"},
  {
    "code": "VCP",
    "name": "Sao Paulo",
    "country": "Brazil",
    "region": "South S. Amer.",
    "latLng": "-23.006982, -47.137812"
  },
  {
    "code": "VLN",
    "name": "Valencia",
    "country": "Venezuela",
    "region": "N. S Amer.",
    "latLng": "10.7661417,-69.4987965"
  },
  {"code": "VSA", "name": "Villahermosa", "country": "Mexico", "region": "Mexico", "latLng": "17.7256917,-94.7355661"},
  {
    "code": "VVI",
    "name": "Santa Cruz",
    "country": "Bolivia",
    "region": "South S. Amer.",
    "latLng": "-16.9613763,-64.5565869"
  },
  {"code": "YUL", "name": "Montreal", "country": "Canada", "region": "US, AK, Can", "latLng": "45.6654086,-74.2591224"},
  {
    "code": "YYZ",
    "name": "Lester B Pearson Intl",
    "country": "Canada",
    "region": "US, AK, Can",
    "latLng": "43.7667022,-79.5562173"
  }
].sort(byLanguage);

var categories = {
  "domestic": [
    {
      "name": "Ejecutiva Flex",
      "cabin": "Economy",
      "class": "C",
      "base": 1,
      "bonification": 0.75,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Ejecutiva Promo",
      "class": "D,J",
      "base": 1,
      "bonification": 0.5,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Super Flex",
      "class": "Y,B,M,H",
      "base": 1,
      "bonification": 0.25,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Economica Flex",
      "class": "Q,K,V",
      "base": 1,
      "bonification": 0,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Economica Extra",
      "class": "U,S,W",
      "base": 1,
      "bonification": 0,
      "calification": 1,
      "segmentsForCalification": 1
    }, {
      "name": "Economica Promo",
      "class": "E,L,T",
      "base": 1,
      "bonification": 0,
      "calification": 1,
      "segmentsForCalification": 1
    }
  ],
  "international": [
    {
      "name": "Ejecutiva Flex",
      "cabin": "Economy",
      "class": "C",
      "base": 1,
      "bonification": 0.75,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Ejecutiva Promo",
      "class": "D,J",
      "base": 1,
      "bonification": 0.5,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Economica Flex",
      "class": "Y,B,M,H,Q",
      "base": 1,
      "bonification": 0.25,
      "calification": 1.5,
      "segmentsForCalification": 2
    }, {
      "name": "Economica Extra",
      "class": "K,V,U,S,W,E",
      "base": 1,
      "bonification": 0,
      "calification": 1,
      "segmentsForCalification": 1
    }, {
      "name": "Economica Promo",
      "class": "L,T",
      "base": 1,
      "bonification": 0,
      "calification": 1,
      "segmentsForCalification": 1
    }
  ]
};

var statuses = [
  {
    name: "Base",
    bonus: 0
  },
  {
    name: "Silver",
    bonus: 0.25
  }, {
    name: "Gold",
    bonus: 0.5
  }, {
    name: "Platinum",
    bonus: 0.75
  }, {
    name: "Presidential Platinum",
    bonus: 1
  }
];

var domesticFlights = [
  ["CTG", "ADZ"],
  ["ADZ", "CTG"],
  ["CLO","BOG"],
  ["BOG","CLO"],
  ["CLO","ADZ"],
  ["ADZ","CLO"],
  ["MDE","BOG"],
  ["BOG","MDE"],
  ["BAQ","ADZ"],
  ["ADZ","BAQ"],
  ["BOG","ADZ"],
  ["ADZ","BOG"],
  ["BOG","ADZ"],
  ["PEI","ADZ"],
  ["ADZ","PEI"]
];

var earnMilesCities = countries.map(function(elem){
  return {value:elem.code, latLng: elem.latLng}
});

var positionCities = {};
earnMilesCities.forEach(function(elem){
  positionCities[elem.value] = {latLng: elem.latLng};
});

ComboData = {
  places : earnMilesCities,
  status : [
    { value: "Base", text: "Base" },
    { value: "Silver", text: "Silver" },
    { value: "Gold", text: "Gold" },
    { value: "Platinum", text: "Platinum" },
    { value: "Presidential Platinum", text: "Presidential Platinum" }
  ],
  flightTypes: [
    { value: "1", text: "One-Way" },
    { value: "2", text: "Roundtrip" }
  ],
  cabin:  [
    { value: "Economy", text: "Economy" },
    { value: "Business", text: "Business" }
  ]
};